apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-auth-preload-data-config
  labels:
    name: mysql-auth-data-store
    app: payments
  namespace: development
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS`auth`;
    USE `auth`;
    DROP TABLE IF EXISTS `user`;
    CREATE TABLE `user`(
     `id`int NOT NULL AUTO_INCREMENT,
     `user_id`varchar(255) NOT NULL UNIQUE,
     `password`varchar(255) NOT NULL,
      PRIMARY KEY (`id`)
    );
    insert into user(`user_id`,`password`) values('maztest8911@gmail.com','winter');`