apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-auth-initdb-config
data:
  init.sql: |
    CREATE DATABASE auth;

    USE auth;

    CREATE TABLE user (
        id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        user_id VARCHAR(255) NOT NULL UNIQUE,
        password VARCHAR(255) NOT NULL
    );

    INSERT INTO user (user_id, password) VALUES ('maztest8911@gmail.com', 'Admin123');