apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-auth
spec:
  selector:
    matchLabels:
      app: mysql-auth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-auth
    spec:
      containers:
      - image: mysql:latest
        name: mysql-auth
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-auth-secret
              key: password
        ports:
        - containerPort: 3306
          name: mysql-auth
        volumeMounts:
        - name: mysql-auth-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-auth-initdb
          mountPath: /docker-entrypoint-initdb.d/init.sql
      volumes:
      - name: mysql-auth-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-auth-pv-claim
      - name: mysql-auth-initdb
        configMap:
          name: mysql-auth-initdb-config