apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-auth
  labels:
    name: mysql-auth
    app: payments
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-auth-pod
      app: payments
  template:
    metadata:
      name: mysql-auth-pod
      labels:
        name: mysql-auth-pod
        app: payments
    spec:
      containers:
        - name: mysql-auth
          image: mysql:8.0.32
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-auth-secret
                  key: root-password
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
            - name: mysql-data
              mountPath: "/var/lib/mysql"
              subPath: "mysql"
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-auth-preload-data-config
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-auth-data-store