apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-auth-pv-volume
  labels:
    type: local
spec:
  storageClassName: standard-rwo
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-auth-pv-claim
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi