apiVersion: apps/v1
kind: Deployment
metadata:
  name: money-movement
  labels:
    name: money-movement
    app: money-movement
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: money-movement
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: money-movement
    spec:
      containers:
        - name: money-movement
          image: mmcferren/money-movement:v2
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: money-movement-configmap
            - secretRef:
                name: money-movement-secret