apiVersion: v1
kind: Service
metadata:
  name: money-movement
  namespace: development
spec:
  type: ClusterIP
  selector:
    app: money-movement
  ports:
    - port: 7000
      targetPort: 7000
      protocol: TCP