apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-money-movement-preload-data-config
  labels:
    name: mysql-money-movement-data-store
    app: payments
  namespace: development
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS`money_movement`;
    USE `money_movement`;
    DROP TABLE IF EXISTS `wallet`;
    CREATE TABLE `wallet`(
     `id`int NOT NULL AUTO_INCREMENT,
     `user_id`varchar(255) NOT NULL,
     `wallet_type`varchar(255) NOT NULL,
      PRIMARY KEY (`id`),
      INDEX(user_id)
    );

    DROP TABLE IF EXISTS `account`;
    CREATE TABLE `account`(
     `id`int NOT NULL AUTO_INCREMENT,
     `cents`int NOT NULL DEFAULT 0,
     `account_type`varchar(255) NOT NULL,
     `wallet_id`int NOT NULL,
      PRIMARY KEY (`id`),
      FOREIGN KEY (wallet_id) REFERENCES wallet(id)
    );

    DROP TABLE IF EXISTS `transaction`;
    CREATE TABLE `transaction`(
     `id`int NOT NULL AUTO_INCREMENT,
     `pid`varchar(255) NOT NULL,
     `src_user_id`varchar(255) NOT NULL,
     `dst_user_id`varchar(255) NOT NULL,
     `src_wallet_id`int NOT NULL,
     `dst_wallet_id`int NOT NULL,
     `src_account_id`int NOT NULL,
     `dst_account_id`int NOT NULL,
     `src_account_type`varchar(255) NOT NULL,
     `dst_account_type`varchar(255) NOT NULL,
     `final_dst_merchant_wallet_id`int,
     `amount`int NOT NULL,
      PRIMARY KEY (`id`),
      INDEX(pid)
    );

    -- merchant and customer wallets
    insert into wallet(`id`,`user_id`, `wallet_type`) values(1, 'maztest8911@gmail.com', 'CUSTOMER');
    insert into wallet(`id`,`user_id`, `wallet_type`) values(2, 'merchant_id', 'MERCHANT');
   
    -- customer accounts
    insert into account(`cents`,`account_type`, `wallet_id`) values(5000000, 'DEFAULT', 1);
    insert into account(`cents`,`account_type`, `wallet_id`) values(0, 'PAYMENT', 1);
   
    -- merchant accounts
    insert into account(`cents`,`account_type`, `wallet_id`) values(0, 'INCOMING', 2);

