apiVersion: v1
kind: Service
metadata:
  name: mysql-movement-service
  labels:
    name: mysql-movement-service
    app: payments
  namespace: development
spec:
  type: ClusterIP
  selector:
    name: mysql-movement-pod
    app: payments
  ports:
    - port: 3306
      targetPort: 3306