apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-money-movement-data-store
  labels:
    name: mysql-money-movement-data-store
    app: payments
  namespace: development
spec:
  resources:
    requests:
      storage: 3Gi
    limits:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo